name = "openid-connect"
type = "javascript"
workers_dev = true

[durable_objects]
classes = [
  { binding = "DO_OIDC", class_name = "OpenIDConnectDurableObject" },
]

[triggers]
crons = ["* * * * *"]

[build]
command = "yarn install && yarn build"
upload_format = "modules"
cwd = "."
watch_dir = "src"
upload_dir = "dist"
upload_exclude = ["*.map"]
