name = "openid-connect"
type = "javascript"
workers_dev = false
compatibility_date = "2021-10-02"

#zone_id = "your-zone-id"
#routes = ["oidc.example.com/*"]

[durable_objects]
classes = [
  { binding = "DO_OIDC", class_name = "OpenIDConnectDurableObject" },
]

[triggers]
crons = ["* * * * *"]

[build]
command = "yarn install && yarn build"
cwd = "."
watch_dir = "src"

[build.upload]
format = "modules"
main = "main.mjs"
